/**
 * 🧩 TestButton – Vantage Lane UI v3.0.0
 * Generated on 2025-10-20T00:24:01.157Z
 * Type: base
 */

import type { Meta, StoryObj } from '@storybook/react';
import { TestButton } from './TestButton';

const meta: Meta<typeof TestButton> = {
  title: 'UI/TestButton',
  component: TestButton,
  parameters: {
    docs: { description: { component: 'Generated by Vantage Lane UI generator v3.0.0.' } },
    controls: { expanded: true },
  },
  argTypes: {
    as: { control: 'select', options: ['div', 'button', 'span', 'section'] },
    variant: { control: 'select', options: ['default', 'primary', 'secondary'] },
    size: { control: 'select', options: ['sm', 'md', 'lg'] },
  }
};

export default meta;
type Story = StoryObj<typeof TestButton>;

export const Default: Story = { args: { children: 'TestButton', variant: 'default' } };
export const Primary: Story = { args: { children: 'Primary', variant: 'primary' } };
export const Secondary: Story = { args: { children: 'Secondary', variant: 'secondary' } };
export const AllSizes: Story = {
  render: () => (
    <div className="flex items-center gap-4">
      <TestButton size="sm">Small</TestButton>
      <TestButton size="md">Medium</TestButton>
      <TestButton size="lg">Large</TestButton>
    </div>
  )
};
