/**
 * 🧩 PremiumButton – Vantage Lane UI v3.0.0
 * Generated on 2025-10-20T00:29:37.491Z
 * Type: base
 */

import type { Meta, StoryObj } from '@storybook/react';
import { PremiumButton } from './PremiumButton';

const meta: Meta<typeof PremiumButton> = {
  title: 'UI/PremiumButton',
  component: PremiumButton,
  parameters: {
    docs: { description: { component: 'Generated by Vantage Lane UI generator v3.0.0.' } },
    controls: { expanded: true },
  },
  argTypes: {
    as: { control: 'select', options: ['div', 'button', 'span', 'section'] },
    variant: { control: 'select', options: ['default', 'primary', 'secondary'] },
    size: { control: 'select', options: ['sm', 'md', 'lg'] },
  }
};

export default meta;
type Story = StoryObj<typeof PremiumButton>;

export const Default: Story = { args: { children: 'PremiumButton', variant: 'default' } };
export const Primary: Story = { args: { children: 'Primary', variant: 'primary' } };
export const Secondary: Story = { args: { children: 'Secondary', variant: 'secondary' } };

export const Loading: Story = { args: { children: 'Loading...', variant: 'primary', loading: true } };
export const Disabled: Story = { args: { children: 'Disabled', variant: 'primary', disabled: true } };

export const AsButton: Story = { 
  args: { 
    as: 'button',
    children: 'Click Me', 
    variant: 'primary',
    onClick: () => alert('Clicked!')
  } 
};

export const AllSizes: Story = {
  render: () => (
    <div className="flex items-center gap-4">
      <PremiumButton size="sm">Small</PremiumButton>
      <PremiumButton size="md">Medium</PremiumButton>
      <PremiumButton size="lg">Large</PremiumButton>
    </div>
  )
};

export const LoadingStates: Story = {
  render: () => (
    <div className="flex items-center gap-4">
      <PremiumButton variant="primary" loading>Loading</PremiumButton>
      <PremiumButton variant="secondary" loading>Processing</PremiumButton>
      <PremiumButton variant="default" disabled>Disabled</PremiumButton>
    </div>
  )
};
