// This file will be auto-generated by Supabase CLI
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  // Database types will be generated by supabase gen types
}
